fail_fast: true
default_install_hook_types: [pre-commit, post-checkout, post-merge]

repos:
- repo: local
  hooks:
    - id: poetry-check
      name: poetry-check
      description: run poetry check to validate config
      entry: poetry check
      language: python
      pass_filenames: false
      stages: [pre-commit]
      files: ^(.*/)?pyproject\.toml$

    - id: poetry-lock
      name: poetry-lock
      description: run poetry lock to update lock file
      entry: poetry lock
      language: python
      pass_filename: false
      stages: [pre-commit]
      files: ^(.*/)?(poetry\.lock|pyproject\.toml)$

    - id: poetry-sync
      name: poetry-sync
      description: run poetry sync to install dependencies from the lock file
      entry: poetry sync
      args: ["--no-root"]
      lanuage: system
      pass_filenames: false
      stages: [post-checkout, post-merge]

    - id: black
      name: black
      description: run black formatter
      entry: poetry run black .
      language: system
      stages: [pre-commit]
      types: [python]

    - id: isort
      name: isort
      description: poetry run isort .
      language: system
      stages: [pre-commit]
      types: [python]
    
    - id: nbqa-black
      name: nbqa-black
      description: run black formatter on Jupyter notebooks
      entry: nbqa black .
      language: python
      pass_filenames: false
      stages: [pre-commit]
      files: \.ipynb$

    # - id: nbqa-isort
    #   name: nbqa-isort
    #   description: run isort formatter on Jupyter notebooks
    #   entry: nbqa isort .
    #   language: python
    #   pass_filenames: false
    #   stages: [pre-commit]
    #   files: \.ipynb$
